<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.icbc.agent</groupId>
        <artifactId>agentbe</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>ai-chat</artifactId>
    <name>ai-chat</name>
    <description>ai-chat</description>


    <dependencies>
        <!-- Spring AI Client Chat -->
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-client-chat</artifactId>
            <scope>compile</scope>
        </dependency>


        <dependency>
            <groupId>com.icbc.agent</groupId>
            <artifactId>ai-model</artifactId>
        </dependency>
        <dependency>
            <groupId>com.icbc.agent</groupId>
            <artifactId>ai-intent</artifactId>
        </dependency>
        <dependency>
            <groupId>com.icbc.agent</groupId>
            <artifactId>ai-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>7.0.8</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>
